version: '3.8'

services:
  nextjs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOSTNAME=${HOSTNAME}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:433"
    depends_on:
      - nextjs-app
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge